name: Cargonaut CI/CD and Analyzis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - run: npm i start-server-and-test
    - run: npm i angular-http-server
    - run : npm install cypress --save-dev
    #- run : npx cypress verify
    - name: cypress-run-headless
      run: cypress run --headless --browser chrome
    - name: start-server:ci
      run: angular-http-server --path ./dist/myCargonaut -p 4200
    - name: run-tests
      run: start-server-and-test start-server:ci 4200 cypress-run-headless
    #- name: Test
     # run: npm run test:prod    ++Tests are still not running properly with firebase
    - run: npm run lint
    
  Deployment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      #- run: npm ci && npm run build
      - uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          base_href: /Cargonaut/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/Cargonaut
        
  code-analyzis:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install
          run: curl -L "https://get.spectralops.io/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
        - name: Scan
          run: $HOME/.spectral/spectral scan --ok
      
